name: audiobookbay
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: null
  flutter_svg: null
  html: ^0.15.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  sqflite: ^2.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
